name: Clone and sync repos to ADO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: info 
        shell: bash
        run: |
          set -x
          git --version
          git lfs --version
          python3 --version
          pip3 --version
          az version 
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git config --global url.https://"${{ env.GIT_USER }}":"${{ env.GH_TOKEN }}"@github.com/"${{ env.GIT_USER }}"/.insteadOf https://github.com/"${{ env.GIT_USER }}"/
        env:
           GIT_USER: ${{ secrets.GIT_USERNAME }}
           GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
           GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install PyGithub GitPython

      - name: Run Python script
        shell: bash
        run: |
          set -x 
          echo $RUNNER_TEMP
          python3 may26-sync-repo.py
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}
          ADO_PERSONAL_ACCESS_TOKEN: ${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USER_ORG: ${{ secrets.USER_ORG }}
          GIT_TRACE: 1
      - name: Print annotations
        run: |
          echo "Annotations: ${{ env.GITHUB_OUTPUT }}"
